# Generated by Django 4.0.4 on 2022-05-10 03:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_on_sale_alter_product_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=2500),
        ),
    ]
