# Generated by Django 4.0.4 on 2022-05-10 03:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='review',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500),
        ),
    ]
