# Generated by Django 4.0.4 on 2022-06-06 09:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_reviewrating_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='small_images',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos/products/small'),
            preserve_default=False,
        ),
    ]
