# Generated by Django 4.0.4 on 2022-05-07 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Roaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_starting', models.DateField(null=True)),
                ('monday', models.CharField(choices=[('no shift', 'No Shift'), ('8am - 5pm', '8am - 5pm'), ('9am - 5pm', '9am - 5pm'), ('10am - 5pm', '10am - 5pm')], default='no shift', max_length=20)),
                ('tuesday', models.CharField(choices=[('no shift', 'No Shift'), ('8am - 5pm', '8am - 5pm'), ('9am - 5pm', '9am - 5pm'), ('10am - 5pm', '10am - 5pm')], default='no shift', max_length=20)),
                ('wednesday', models.CharField(choices=[('no shift', 'No Shift'), ('8am - 5pm', '8am - 5pm'), ('9am - 5pm', '9am - 5pm'), ('10am - 5pm', '10am - 5pm')], default='no shift', max_length=20)),
                ('thursday', models.CharField(choices=[('no shift', 'No Shift'), ('8am - 5pm', '8am - 5pm'), ('9am - 5pm', '9am - 5pm'), ('10am - 5pm', '10am - 5pm')], default='no shift', max_length=20)),
                ('friday', models.CharField(choices=[('no shift', 'No Shift'), ('8am - 5pm', '8am - 5pm'), ('9am - 5pm', '9am - 5pm'), ('10am - 5pm', '10am - 5pm')], default='no shift', max_length=20)),
                ('saturday', models.CharField(choices=[('no shift', 'No Shift'), ('8am - 5pm', '8am - 5pm'), ('9am - 5pm', '9am - 5pm'), ('10am - 5pm', '10am - 5pm')], default='no shift', max_length=20)),
                ('sunday', models.CharField(choices=[('no shift', 'No Shift'), ('8am - 5pm', '8am - 5pm'), ('9am - 5pm', '9am - 5pm'), ('10am - 5pm', '10am - 5pm')], default='no shift', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
